#!/usr/bin/env python3

import subprocess
import os
import argparse


# Get user running script
SUDOER = os.environ.get('SUDO_USER')
USER = os.getlogin()
# Exit if user not sudo
if not SUDOER or USER == "root":
    print("Script must be run as root!")
    exit()


# Constants
CACHE_DIR = f"/home/{USER}/.cache/secureread/"


def depend_check() -> None:
    SUPPORTED_DISTROS = ["ubuntu"]
    distro_id = check_distro()

    # Quit if the distro is not supported
    if distro_id.lower() not in SUPPORTED_DISTROS:
        print(f"[Err] This distrobution is not supported.\nSupported: {SUPPORTED_DISTROS}")
        exit(1)

    # Test commands
    test_curl = "which curl"
    test_nxagent = "which nxagent"
    test_x11docker = "which x11docker"
    test_docker = "which docker"
    # Flag variables
    curl_status = True
    nxagent_status = True
    x11docker_status = True
    docker_status = True

    test_curl_result = subprocess.run(
        test_curl, 
        capture_output=True, 
        text=True,
        shell=True,
        )
    
    test_nxagent_result = subprocess.run(
        test_nxagent, 
        capture_output=True, 
        text=True,
        shell=True,
        )
    
    test_docker_result = subprocess.run(
        test_docker, 
        capture_output=True, 
        text=True,
        shell=True,
        )
    
    test_x11docker_result = subprocess.run(
        test_x11docker, 
        capture_output=True, 
        text=True,
        shell=True,
        )
    
    # Set flag variables based on return codes
    if test_curl_result.returncode != 0:
        curl_status = False
    if test_nxagent_result.returncode != 0:
        nxagent_status = False
    if test_docker_result.returncode != 0:
        docker_status = False
    if test_x11docker_result.returncode != 0:
        x11docker_status = False

    if curl_status == False or x11docker_status == False or docker_status == False:
        print("secureread requires the following dependancies:")
        print("  docker\n  x11docker\n  curl")
        install_choice = input("Would you like to install missing dependencies? (y/N) > ")
        if install_choice.lower() == "y":
            install_ubuntu_depend(curl_status, nxagent_status, docker_status, x11docker_status)


# Try to read /etc/os-release (standard for modern Linux)
def check_distro() -> str:
    if os.path.exists("/etc/os-release"):
        with open("/etc/os-release", "r") as f:
            for line in f:
                line = line.strip()
                if line.startswith("ID="):
                    dist_id = line.split("=")[1].strip('"')
        return dist_id


# Install dependancies for Ubuntu
def install_ubuntu_depend(curl:bool, nxagent:bool, docker:bool, x11docker:bool) -> None:
    APT_UPDATE = "apt update -y"
    INSTALL_CURL = "apt install curl -y"
    INSTALL_NXAGENT = "apt install nxagent -y"
    INSTALL_DOCKER = "snap install docker"
    INSTALL_X11DOCKER = "curl -fsSL https://raw.githubusercontent.com/mviereck/x11docker/master/x11docker | sudo bash -s -- --update"

    # Update apt
    print("--> Updating apt...")
    try:
        os.system(APT_UPDATE)
    except Exception as e:
        print(f"[Err] Unable to update apt. [install_ubuntu_depend]\n Err: {e}")
        exit(1)

    # install curl
    if curl == False:
        print("--> Installing curl...")
        try:
            os.system(INSTALL_CURL)
            print("Successfully installed curl!")
        except Exception as e:
            print(f"[Err] Unable to install curl. [install_ubuntu_depend]\n Err: {e}")

    if nxagent == False:
        print("--> Installing nxagent...")
        try:
            os.system(INSTALL_NXAGENT)
            print("Successfully installed nxagent!")
        except Exception as e:
            print(f"[Err] Unable to install nxagent. [install_ubuntu_depend]\n Err: {e}")

    if docker == False:
        print("--> Installing docker...")
        try:
            os.system(INSTALL_DOCKER)
            print("Successfully installed docker!")
        except Exception as e:
            print(f"[Err] Unable to install docker. [install_ubuntu_depend]\n Err: {e}")

    if x11docker == False:
        print("--> Installing x11docker...")
        try:
            os.system(INSTALL_X11DOCKER)
            print("Successfully installed x11docker!")
        except Exception as e:
            print(f"[Err] Unable to install x11docker. [install_ubuntu_depend]\n Err: {e}")


def create_docker_file():
    print("here")
    os.system(f"echo 'FROM ubuntu:24.04' > {CACHE_DIR}dockerfile")
    os.system(f"echo 'RUN apt update -y' >> {CACHE_DIR}dockerfile")
    os.system(f"echo 'RUN apt upgrade -y' >> {CACHE_DIR}dockerfile")
    os.system(f"echo 'RUN apt install evince -y' >> {CACHE_DIR}dockerfile")


def setup_docker_image() -> str:
    # Constants
    IMAGE_TAG = "secureread"
    DOCKER_BUILD = f"docker build -t {IMAGE_TAG} {CACHE_DIR}"

    #Create CACHE and CONFIG directory if it does not exist
    if not os.path.exists(CACHE_DIR):
        os.mkdir(CACHE_DIR)
    
    if not os.path.exists(f"{CACHE_DIR}dockerfile"):
        configure_docker = input("Would you like to configure the docker container? (y/N) > ")
        if configure_docker.lower() == "y":
            try:
                create_docker_file()
                os.system(DOCKER_BUILD)
            except Exception as e:
                print(f"[Err] Unable to configure docker [setup_docker_image]\nErr: {e}")
                exit(1)
        else:
            print("Exiting...")
            exit(0)
    
    return IMAGE_TAG


def open_pdf_file(path:str):
    image_tag = setup_docker_image()
    x11docker_command = f"x11docker --nxagent {image_tag} --clipboard --share {path} evince {path}"
    os.system(x11docker_command)


def main():
    #Set up parser module with command arguments
    parser = argparse.ArgumentParser(description="secureread script")

    #Initialize parser arguments
    parser.add_argument("-p", type=str, help="Specify path for a pdf file to pass.")
    parser.add_argument("--setup", action="store_true", help="Setup sunderapp")

    args = parser.parse_args()
    
    if args.setup == True:
        try:
            depend_check()
        except Exception as e:
            print(f"[Err] Unable to setup dependancies [main]\nErr: {e}")
            exit(1)
        try:
            setup_docker_image()
        except Exception as e:
            print(f"[Err] Unable to setup dependancies [main]\nErr: {e}")
            exit(1)
    if args.p != None:
        open_pdf_file(args.p)


main()